apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store-redis
  namespace: portfolio-backend
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: redis-secret
            namespace: portfolio-backend