apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.46.8
    helm:
      values: | 
        logLevel: info
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush {{ .Values.flush }}
                Log_Level debug
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort }}
                Health_Check On
                Trace_Error On

          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*portfolio-backend*.log
                multiline.parser docker, cri
                Tag kube.portfolio-backend.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

            [INPUT]
                Name tail
                Path /var/log/containers/*portfolio-ui*.log
                multiline.parser docker, cri
                Tag kube.portfolio-ui.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On

            [INPUT]
                Name tail
                Path /var/log/containers/*nginx*.log
                multiline.parser docker, cri
                Tag kube.ingress.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.portfolio-backend.*
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On

            [FILTER]
                Name kubernetes
                Match kube.portfolio-ui.*
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On

            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On

            [FILTER]
                Name parser
                Match kube.ingress.*
                Key_Name log
                Parser nginx
                Reserve_Data On

          ## https://docs.fluentbit.io/manual/pipeline/outputs
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Index fluent-bit
                Type  _doc
                Host elasticsearch-master
                Port 9200
                HTTP_User elastic
                HTTP_Passwd 9fVpTSmmeC3IzEiE
                tls Off
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix logstash
                Retry_Limit False
                Suppress_Type_Name On

            [OUTPUT]
                Name es
                Match host.*
                Index fluent-bit
                Type  _doc
                Host elasticsearch-master
                Port 9200
                HTTP_User elastic
                HTTP_Passwd 9fVpTSmmeC3IzEiE
                tls Off
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix node
                Retry_Limit False
                Suppress_Type_Name On

          customParsers: |
            [PARSER]
                Name json_parser
                Format json
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%NZ

            [PARSER]
                Name regex_parser
                Format regex
                Regex /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
                Time_Format %Y-%m-%dT%H:%M:%S.%N%:z

            [PARSER]
                Name nginx
                Format regex
                Regex ^(?<remote>[^ ]*) - (?<user>[^ ]*) \\[(?<time>[^\\]]*)\\] "(?<method>\\S+)(?: +(?<path>[^\\"]*?)(?: +\\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\\"]*)" "(?<agent>[^\\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \\[(?<proxy_upstream_name>[^ ]*)\\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<host>[^ ]*) (?<server_protocol>[^ ]*)
                Time_Key time
                Time_Format %d/%b/%Y:%H:%M:%S %z

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true