apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 7.17.3
    helm:
      values: | 
        elasticsearchHosts: "http://elasticsearch-master:9200"
        elasticsearchCertificateSecret: elasticsearch-master-certs
        elasticsearchCertificateAuthoritiesFile: ca.crt
        elasticsearchCredentialSecret: elasticsearch-master-credentials

        ingress:  
          enabled: true
          hosts:
            - host: tomer.kibana
              paths:
                - path: /

        resources:
          requests:
            cpu: "100m"
            memory: "512M"
          limits:
            cpu: "1000m"
            memory: "1Gi"

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true