apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email-external-secret
  namespace: portfolio-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store-email
    kind: SecretStore
  target:
    name: email-secret
    creationPolicy: Owner
  data:
    - secretKey: EMAIL_ADDRESS
      remoteRef:
        key: tomer-portfolio-env
        property: EMAIL_ADDRESS
    - secretKey: EMAIL_PASSWORD
      remoteRef:
        key: tomer-portfolio-env
        property: EMAIL_PASSWORD
    - secretKey: MY_EMAIL_ADDRESS
      remoteRef:
        key: tomer-portfolio-env
        property: MY_EMAIL_ADDRESS