apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store-email
  namespace: portfolio-backend
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: email-secret
            namespace: portfolio-backend