apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: model-external-secret
  namespace: portfolio-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store-model
    kind: SecretStore
  target:
    name: model-secret
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: tomer-portfolio-env
        property: GOOGLE_API_KEY
    - secretKey: GOOGLE_MODEL_NAME
      remoteRef:
        key: tomer-portfolio-env
        property: GOOGLE_MODEL_NAME