apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.frontApp.name }}-service
  namespace: {{ .Values.frontend.namespace }}
spec:
  selector:
    app: {{ .Values.frontend.frontApp.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.frontApp.service.port }}
      targetPort: {{ .Values.frontend.frontApp.service.port }}
  type: {{ .Values.frontend.frontApp.service.type }}