apiVersion: batch/v1
kind: Job
metadata:
  name: install-cert-manager-crds
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: cert-manager-admin
      containers:
        - name: crd-installer
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml
      restartPolicy: OnFailure