apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: portfolio-backend
  namespaceSelector:
    matchNames:
      - portfolio-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s