apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-external-secret
  namespace: portfolio-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store-mongo
    kind: SecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: tomer-portfolio-env
        property: MONGO_USERNAME
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: tomer-portfolio-env
        property: MONGO_PASSWORD