{{- if .Values.ingress.externalNameBackend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.ingress.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.app.name }}.{{ .Values.backNamespace }}.svc.cluster.local
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}