apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store-mongodb
  namespace: mongodb
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: mongodb-secret
            namespace: mongodb